### ISSUE TITLE
repo  관련 오류입니다.

### ISSUE THREAD

**Issue by sansanai** [HaloKim/chatKoAlpaca#1]
안녕하세요... 공개해주신 노트북 파일을 구글코랩pro에서 테스트 해볼려고 합니다.
첫번째 단계 SFT 지도 학습 단계에서 import 라이브러리 후, model name을 이용해서 tokenizer를 생성할 때 
다음과 같은 오류가 납니다.

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 
'KoAlpaca/train_v1.1b/polyglot-1.3b-koalpaca-v1.1b'. Use `repo_type` argument if needed.

혹시 몰라서 허깅페이스 사이트에서 polyglot-1.3b로 필터링 했는데, notebook에 기술된 model 이름이 안보이네요...

혹시 sharpian/polyglot-1.3b-koalpaca-v1.1b-03 를 사용해야 하는 건지 궁금합니다.

**Comment by HaloKim** [comment]
안녕하세요 @sansanai 님

질문하신 내용의 모델은 koalpaca 원본 레포를 참조하셔서 만드시면 됩니다.

```
베이스 모델을 Alpaca 데이터셋으로 Finetune을 진행하고,

Alpaca 모델을 ColossalAI를 활용하여 chat Finetune하는 과정을 거칩니다.
```
